language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5

install:
  - go get -d -v ./... && go build -v ./...
  - go get -u github.com/stretchr/testify/assert
  - go get -u golang.org/x/tools/cmd/cover

script:
  - go test -bench . -race
  - go test -bench .